---

version: "3"

services:
  s3:
    image: e2r5/s3payment
    ports:
      - "8000"
    environment:
      MICROPAYMENT_SERVER: micropayment:8001

  lb:
    image: zenko/loadbalancer
    ports:
      - "80:80"
    environment:
      LISTEN_PORT: 80
      UPSTREAM_SERVER: s3:8000

  micropayment:
    image: e2r5/micropayment
    ports:
      - "8001"
    environment:
      GETH_SERVER: geth:8545

  geth:
    image: ethereum/client-go
    command: --testnet --fast --cache=512 --rpc --rpcaddr 0.0.0.0 --mine --password /root/passwd --unlock 0
    volumes:
      - "/geth_data:/root"
    ports:
      - "8545"
      - "30303"
